
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "MRSlouzk", email = "MRSlouu@163.com"},
]
dependencies = [
    "click>=8.1.6",
    "loguru>=0.7.0",
]
requires-python = ">=3.8"
license = {text = "MIT"}
